### ISSUE TITLE
Ajouter de très nombreux commerces

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#255]
Dans l'optique de créer un éditeur carto pour tous les commerces utilisable sur le terrain sur commerces.openstreetmap.fr :

- [ ] [Lister tous les commerces souhaités](https://github.com/vdct/ProjetDuMois/issues/254)
- [ ] [Créer une icône générique](https://github.com/vdct/ProjetDuMois/issues/268) (utilisée par défaut)
- [ ] [Créer toutes les icônes associées] (_nice-to-have_)
- [ ] Identifier les tags principaux / tags secondaires / mots-clefs pour auto-complétion de la barre de recherche
- [ ] Créer une carte où s'affiche tout type de POI
- [ ] Repenser l'arborescence du site en conséquence
- [ ] Créer le menu de la carte, incluant notamment la sélection de type de POI (incluant plusieurs centaines de type de lieux / sous-rubriques) ([plus élaboré donc que celui actuellement imaginé](https://github.com/vdct/ProjetDuMois/issues/238))
- [ ] Créer un menu de sélection de type de POI (utile lorsque l'on clique sur "créer un lieu manquant" (qui sera un gros bouton (+) sur la carte)

Sans oublier le travail préliminaire :
- [x] [Changer le logo](https://github.com/vdct/ProjetDuMois/issues/258)
- [x] [Changer le sous-titre](https://github.com/vdct/ProjetDuMois/issues/257)

**Comment by PanierAvide** [comment]
Je ferme ce ticket, l'approche 1 projet + menu déroulant pour choisir le commerce a bien fonctionné
