### ISSUE TITLE
Mettre en ligne "tu veux ma photo"

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#81]
Suite à https://github.com/vdct/ProjetDuMois/issues/74 et https://github.com/vdct/ProjetDuMois/issues/77 et https://github.com/vdct/ProjetDuMois/issues/66 :
Pour alimenter le projet du mois avec plus de signalements utilisateurs, montons le site https://tuveuxmaphoto.fr avec une interface dédiée aux utilisateurs qui n'ont pas de compte OSM (persona "les noobs").
A faire :
- [X] Acheter le nom de domaine https://tuveuxmaphoto.fr
- [ ] Configurer les DNS
- [ ] Créer [la page d'accueil](https://github.com/vdct/ProjetDuMois/issues/87) (avec /à propos d'osm)
- [X] Créer [le logo](https://github.com/vdct/ProjetDuMois/issues/88)
- [ ] Créer [les mentions légales + conditions d'utilisation + règles communautaires](https://github.com/vdct/ProjetDuMois/issues/91)
- [ ] Créer la page "Cookies"
- [ ] Créer le site qui permet d'envoyer des photos géolocalisées avec commentaires
- [ ] Créer [l'interface pour gérer les retours coté "projet du mois"](https://github.com/vdct/ProjetDuMois/issues/82)

**Comment by overflorian** [comment]
Mockups de ce service (annule et remplace https://github.com/vdct/ProjetDuMois/issues/77) :

**Comment by overflorian** [comment]
Dans le MVP, on demande au parrain son prénom + le prénom du filleul.
Il envoie l'URL qui respecte la structure https://url.fr/{numéro de relation parrain-filleul}/prénom-du-filleul
La phrase de bienvenue personnalisée s'affiche.

**Comment by overflorian** [comment]
![IMG_20201007_165818.jpg](https://user-images.githubusercontent.com/11553211/95361045-81440000-08cc-11eb-99f2-b2ec49012953.jpg)

![IMG_20201007_173240_1.jpg](https://user-images.githubusercontent.com/11553211/95361142-a33d8280-08cc-11eb-844d-758263f49010.jpg)

![IMG_20201007_175806_1.jpg](https://user-images.githubusercontent.com/11553211/95361168-ac2e5400-08cc-11eb-8341-ba8cb140550c.jpg)

![Screenshot_20201007-171118__01.jpg](https://user-images.githubusercontent.com/11553211/95361185-b3edf880-08cc-11eb-892a-f9c251c05898.jpg)
